### ISSUE TITLE
No confirmation page for adding in data manually

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#12]
There's an option to add in survey data manually rather than sending it out - after completing that form there is also no confirmation page or thank you page. It's the same blank page as last time.

**Comment by bikash02** [comment]
Please try to recheck once again I have tested and its working for me.
![screenshot-cleonix biz 2016-11-04 20-50-49](https://cloud.githubusercontent.com/assets/16361011/20011105/7bc61d4a-a2d0-11e6-97ba-c361a257281e.png)

**Comment by bikash02** [comment]
http://cleonix.biz/faithtrends/login.php?ref=MTg%3D&&ref1=MjA%3D

**Comment by camerontrimble** [comment]
I just tested and it is working for me. Good job on that. We need to make the process "pretty" with different colors/design, but that can come later.

**Comment by bikash02** [comment]
Thank you for your response!!
Keep me posted I'll update you regarding the design..

**Comment by rikalively** [comment]
I still cannot get any confirmation pages. I've tried on both Chrome and Safari.

**Comment by bikash02** [comment]
are you using "admin" or "user" account?

**Comment by debajyotiGuha** [comment]
The problem is fixed now. Please check one more time.

**Comment by rikalively** [comment]
I'm using an admin account. Still cannot get anything. I'm getting this page every time I take a survey or add in data manually. 

<img width="1146" alt="screen shot 2016-11-07 at 9 04 31 am" src="https://cloud.githubusercontent.com/assets/23104131/20060465/48952c90-a4c9-11e6-8a67-95164578fafc.png">

**Comment by debajyotiGuha** [comment]
Please refresh the site with cache clear or just press ctrl+f5 and test one more time. I have checked it in with Dawn Hammond account and it's working fine.

**Comment by rikalively** [comment]
finally got it! thank you!
